"""empty message

Revision ID: f5f5809bdcb8
Revises: 5834fd40bb6b
Create Date: 2019-11-14 15:04:13.672619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f5809bdcb8'
down_revision = '5834fd40bb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    # ### end Alembic commands ###
